/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MenuItem } from "./components/radial-menu/radial-menu";
import { MenuItem as MenuItem1 } from "./components/radial-menu/MenuItem.interface";
export namespace Components {
    interface RadialMenu {
        "centerColor": string;
        "fontColor": string;
        "menuItems": Array<MenuItem>;
        "size": number;
    }
    interface RadialMenuCenter {
        "color": string;
        "size": number;
    }
    interface RadialMenuItems {
        "color": string;
        "isDragging": boolean;
        "menuItems": Array<MenuItem>;
        "size": number;
        "visible": boolean;
    }
}
declare global {
    interface HTMLRadialMenuElement extends Components.RadialMenu, HTMLStencilElement {
    }
    var HTMLRadialMenuElement: {
        prototype: HTMLRadialMenuElement;
        new (): HTMLRadialMenuElement;
    };
    interface HTMLRadialMenuCenterElement extends Components.RadialMenuCenter, HTMLStencilElement {
    }
    var HTMLRadialMenuCenterElement: {
        prototype: HTMLRadialMenuCenterElement;
        new (): HTMLRadialMenuCenterElement;
    };
    interface HTMLRadialMenuItemsElement extends Components.RadialMenuItems, HTMLStencilElement {
    }
    var HTMLRadialMenuItemsElement: {
        prototype: HTMLRadialMenuItemsElement;
        new (): HTMLRadialMenuItemsElement;
    };
    interface HTMLElementTagNameMap {
        "radial-menu": HTMLRadialMenuElement;
        "radial-menu-center": HTMLRadialMenuCenterElement;
        "radial-menu-items": HTMLRadialMenuItemsElement;
    }
}
declare namespace LocalJSX {
    interface RadialMenu {
        "centerColor"?: string;
        "fontColor"?: string;
        "menuItems"?: Array<MenuItem>;
        "size"?: number;
    }
    interface RadialMenuCenter {
        "color"?: string;
        "size"?: number;
    }
    interface RadialMenuItems {
        "color"?: string;
        "isDragging"?: boolean;
        "menuItems"?: Array<MenuItem>;
        "size"?: number;
        "visible"?: boolean;
    }
    interface IntrinsicElements {
        "radial-menu": RadialMenu;
        "radial-menu-center": RadialMenuCenter;
        "radial-menu-items": RadialMenuItems;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "radial-menu": LocalJSX.RadialMenu & JSXBase.HTMLAttributes<HTMLRadialMenuElement>;
            "radial-menu-center": LocalJSX.RadialMenuCenter & JSXBase.HTMLAttributes<HTMLRadialMenuCenterElement>;
            "radial-menu-items": LocalJSX.RadialMenuItems & JSXBase.HTMLAttributes<HTMLRadialMenuItemsElement>;
        }
    }
}
